<?php

namespace Abryb\ENadawca\Enum;

class PrintKindEnum {
    const ADDRESS_LABEL = 'ADDRESS_LABEL';
    const ADDRESS_LABEL_BY_GUID = 'ADDRESS_LABEL_BY_GUID';
    const CUSTOMS_DECLARATION = 'CUSTOMS_DECLARATION';
    const ADDRESS_LABEL_FOR_RETURN_DOCUMENTS = 'ADDRESS_LABEL_FOR_RETURN_DOCUMENTS';
    const CHECKLIST = 'CHECKLIST';
    const COLLECT_ON_DELIVERY_FORM = 'COLLECT_ON_DELIVERY_FORM';
    const WAYBILL = 'WAYBILL';
    const REPORT = 'REPORT';
    const ADDRESS_LABEL_FOR_ERETURN = 'ADDRESS_LABEL_FOR_ERETURN';
    const ADDRESS_LABEL_FOR_FOREGIN_RETURN = 'ADDRESS_LABEL_FOR_FOREGIN_RETURN';
}